print('           ESCAPE')
print('   from blockyGames studio')
print('          good luck')
print(' ')
print('Story 1:')
from random import randint
from time import sleep
door = randint(1, 3)
print('A dark night ')
print('There is a power failure')
print('Zombies destory the city')
print('A Zombie behind you')
print('RUN!')
print('...')
sleep(5)
print('')
print('')
print('')
print('')
print('')
print('A house')
print('you go in')
print('three doors')
print('Where you go in?')